### ISSUE TITLE
Binary file to download?

### ISSUE THREAD

**Issue by precondition** [FromtonRouge/KaladriusTrainer#1]
I'm interested to use this program to learn Jackdaw but I can't find anywhere a binary file I can download and my attempts to compile the program myself bumped into many dependency issues and generator issues. 

Installing libboost and QT on Linux is straightforward but on Windows, it's rather confusing. I found a .zip file for libboost but I don't know where to put it. The cmake file seems to say that I should put it in `C:\` so that's where I put it. As for QT, it seems like I need to create an account and pay before I can even download it?

Am I right to believe this only works on Windows? Would it work with Wine under Linux, you think?

Sorry for all those noob questions. This is all very new to me.

**Comment by FromtonRouge** [comment]
There is no binary because this application is in very early development stage

It's been a long time since I compiled this project. Last time (1 year ago) it compiled and run and both Windows and Ubuntu. I use Qt Creator to build this project both on windows and linux

For Qt you don't need to pay there is an Open Source version : https://www.qt.io/download-open-source (but I think you still need an account I don't remember)

For Windows only
- Install Visual Studio 2019 Community

For both Windows and Ubuntu
- Install and run the Qt Maintenance tool 
- Select Qt 5.15.0 for your compiler
![image](https://user-images.githubusercontent.com/1663920/86919844-1d713600-c129-11ea-8dd1-7df8cebddfe0.png)
- And also the debugger support
![image](https://user-images.githubusercontent.com/1663920/86919927-3bd73180-c129-11ea-902c-831253b084cf.png)

For Boost you can build the boost-serialization library only. More info here https://www.boost.org/doc/libs/1_73_0/more/getting_started/windows.html

Now in QtCreator

- Open the file CMakeLists.txt from QtCreator
- Select the Qt toolkit
![image](https://user-images.githubusercontent.com/1663920/86961705-f1be7200-c161-11ea-992b-87d67bb8de02.png)
- Click "Configure Project"
- Change CMake parameters in the "Projects" tab
![image](https://user-images.githubusercontent.com/1663920/86962113-a2c50c80-c162-11ea-816c-663a72a23902.png)

- Click on the Play button
![image](https://user-images.githubusercontent.com/1663920/86961981-6b566000-c162-11ea-883e-753b2ae9316d.png)

![image](https://user-images.githubusercontent.com/1663920/86962357-0a7b5780-c163-11ea-985b-21ce0ac5ef79.png)

**Comment by precondition** [comment]
Oh, I'm glad to hear that it works on Ubuntu too so I'll be very grateful if you add instructions for Ubuntu too.

I guess I'll keep trying with QTCreator

**Comment by precondition** [comment]
For the lack of a better communication channel, .... did you have any luck writing French using Jackdaw?

**Comment by FromtonRouge** [comment]
No Jackdaw was designed only for english. The dictionary (the Shelton Table) was designed from english words so it's not suitable for french

**Comment by FromtonRouge** [comment]
There is now a Windows installer here https://github.com/FromtonRouge/KaladriusTrainer/releases
